### ISSUE TITLE
Platoon Gear Storage and Transportation Changes

### ISSUE THREAD

**Issue by Diffusion9** [Diffusion9/Sandbox.Altis#2]
_Initial Draft_

In the original Sandbox squad and platoon storage boxes were teleported via script to their deployment destinations with their inventory intact. When, for example, a patrol base was packed up the storage boxes associated with that base would teleport back to a default location (or the previous tier of base).

Changes:
- In order to disassemble a base all of the storage boxes associated with the base need to be emptied.
- Players must manually transport the equipment in the storage boxes using backpacks and vehicles as appropriate.
- When the new base is setup they will have to transfer the gear into the new boxes.

Ideas:
- Vehicles could have a Load \ Unload Cargo addAction when near cargo containers, this could facilitate quick loading and unloading gear.

**Comment by DEL-J** [comment]
I don't think we should require the storage boxes to be empty before we can dismantle a patrol base. We should just have the objects left behind be destroyed/deleted. We might consider a hint or warning saying something like "Destroy remaining stored items?"

However, HOLY SHIT! That vehicle load/unload addaction is fucking BRILLIANT!

That would be awesome for logistics stuff, instead of forming the trains from the helicopter to the truck, then from the truck to the PB, we could just use that. It would be 'slightly' less immersive, but OVERWHELMINGLY more convenient.

**Comment by Diffusion9** [comment]
Destroying the items is the best bet. Emptying them all on the ground could be catastrophic if somebody decides to empty a container with a large amount of items. I suppose I could set certain limits on the amount of items spawned as a result of a pack-up, but the lazier route is to just hose everything. I will add a YES \ NO confirmation dialog for it.

Deleting the items could be a good way of clean-up anyways; if we've accrued a number of worthless items they can be destroyed without calling in logistics or leaving them behind.

Truck loading and unloading is something useful for sure. Antistasi Altis is the inspiration for that, as it has something similar. I'm sure other scripts have done it before as well.

**Comment by Diffusion9** [comment]
See #36
